plugins {
    id 'com.android.application'
}
android {
    compileSdk 35
    namespace 'com.theo.toycontrol'
    defaultConfig {
        applicationId "com.theo.toycontrol"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
